name: Docker Publish and Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: rental_mobil
    steps:
      # Step 1: Checkout kode dari repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Login ke DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build dan Push Docker Image
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/laravel_franken:latest

      # Step 4: Simpan SSH Key ke File
      - name: Create SSH Key File
        run: |
          echo "${{ secrets.AWS_EC2_KEY }}" | tr -d '\r' > private_key.pem
          chmod 600 private_key.pem

      - name: Debug SSH Connection
        run: |
          ssh -vvv -o StrictHostKeyChecking=no -i private_key.pem ubuntu@${{ secrets.AWS_EC2_IP }} "echo Connected successfully!"

      # Step 5: Deploy ke EC2 Server
      - name: Deploy to EC2 Server
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@${{ secrets.AWS_EC2_IP }} << 'EOF'

          # Pull image terbaru dari DockerHub
          docker pull ${{ secrets.DOCKER_USERNAME }}/laravel_franken:latest

          # Hentikan dan hapus container lama jika ada
          docker stop laravel_app || true
          docker rm laravel_app || true

          # Hapus image lama untuk menghemat storage
          docker system prune -af

          # Jalankan container baru
          docker run -d --name laravel_app -p 80:80 --restart unless-stopped ${{ secrets.DOCKER_USERNAME }}/laravel_franken:latest

          EOF
